Outline and objectives
learnopenscience/TOPS-OC1-ethos pull request #1
Opened 2022-07-21 17:37 UTC by yochannah

Moving in the outline and objectives

2022-07-22 09:15 UTC, Ismael-KG requested changes
Hoping my review helps. The two main comments:
* Add blank spaces between titles in lesson one to be consistent with the remaining lessons (or remove spaces in the remaining lessons!); and
* Drop "What, Why, How, etc." from the start of lesson titles to make them more legible (unless this will be done across all the modules).

2022-07-22 09:15 UTC, Ismael-KG commented on lessons/lesson2.md
> +### Quality and diversity of scholarly communications
I am unsure the content of this subsection adequately covers diversity. This is (as all others) just a suggestion!

```suggestion
### Quality of scholarly communications
```

2022-07-22 09:15 UTC, Ismael-KG commented on lessons/lesson3.md
> +# Lesson 3: WHO: Stakeholders of Open Science: Who practices Responsible Open Science and for whom?
```suggestion
# Lesson 3. Stakeholders of Open Science: Who practices Responsible Open Science and for whom?
```

2022-07-22 09:15 UTC, Ismael-KG commented on lessons/lesson3.md
> +#### Case Scenario #1:  Trend: Public  —> Policy-makers
```suggestion
#### Case Scenario #1:  Trend: Public —> Policy-makers
```

2022-07-22 09:15 UTC, Ismael-KG commented on lessons/lesson4.md
> +# Lesson 4: WHERE: Impact of Open Science on academia,  communities and society as a whole: Where open science happens
```suggestion
# Lesson 4. Impact of Open Science on academia, communities and society as a whole: Where open science happens
```

2022-07-22 09:15 UTC, Ismael-KG commented on lessons/lesson4.md
> +### European case: General Data Protection regulation
```suggestion
### European case: the General Data Protection Regulation
```

2022-07-22 09:15 UTC, Ismael-KG commented on lessons/lesson4.md
> +### United States case
Adding something after a semicolon to follow the pattern of the EU and South African cases above.

```suggestion
### United States case: state legislation
```

2022-07-22 09:15 UTC, Ismael-KG commented on lessons/lesson5.md
> +# Lesson 5: HOW: Open Science resources & tools: How to get started in responsible Open Science (doing open science responsibly)
```suggestion
# Lesson 5: Open Science resources & tools: How to get started in responsible Open Science
```

2022-07-22 09:22 UTC, yochannah commented on lessons/lesson1.md
> +# Lesson 1: WHAT: Intro to Open Science: What is it and what does it promote?
This agrees with something I'd been wondering about - so yes, this is a good idea. Thanks!

2022-07-22 09:26 UTC, yochannah commented on lessons/lesson1.md
> +## Further Reading
addressed in most recent push!

2022-07-23 13:21 UTC, aosman12 approved these changes
Looks Good!

2022-07-23 13:22 UTC, aosman12 approved these changes

2022-07-25 13:11 UTC, merged