Update README.md
learnopenscience/TOPS-OC1-ethos pull request #4
Opened 2022-07-25 14:35 UTC by nasacrawford

Adding the lessons to the README page

2022-08-01 20:43 UTC, yochannah approved these changes

2022-08-01 20:43 UTC, yochannah commented on README.md
> +The full list of objectives and lessons can be found in teh [lessons directory](lessons/).   The Ethos of Open Science module has the following lessons:
```suggestion
The full list of objectives and lessons can be found in the [lessons directory](lessons/).   The Ethos of Open Science module has the following lessons: 
```

2022-08-01 20:49 UTC, yochannah commented
Thanks @nasacrawford ! It looks good to me - I've requested review from one more team member and then we'll merge it in!

2022-08-01 22:31 UTC, aosman12 commented on README.md
> +The full list of objectives and lessons can be found in teh [lessons directory](lessons/).   The Ethos of Open Science module has the following lessons:
Change “lession” for Open Science to “Lesson” for Open Science

2022-08-01 22:37 UTC, aosman12 requested changes
all good ! 
Commented to correct a minor spell check “lession” to “lesson”

2022-08-02 07:47 UTC, msundukova commented
looks good to me.

2022-08-02 09:08 UTC, yochannah commented on README.md
> +## Lession for Open Science
```suggestion
## Lesson for Open Science
```

2022-08-02 09:10 UTC, merged